### ISSUE TITLE
Powermenu.sh functionality not working

### ISSUE THREAD

**Issue by Shahab96** [Axarva/dotfiles-2.0#83]
**Describe the bug**
Currently when using eww, powermenu, or xmonad to log out, restart, shutdown, lock or sleep, the script does not succeed.
Running the respective commands directly in the terminal, eg betterlockscreen -l, does work successfully though. The failure occurs when using the eww/xmonad provided guis

**To Reproduce**
1. Hit Mod+p
2. Click on any of the logout/shutdown/etc buttons
3. Provide y/yes response to the "Are you sure?" prompt
4. There is no error logged

**Expected behavior**
Expected behavior is for the command inside the switch case in powermenu.sh to succeed.

**Screenshots**
Not really sure how to post a screenshot of these commands not succeeding since they don't produce any readable outputs.

**Desktop (please complete the following information):**
 - OS: Archcraft

**Additional context**
Attached neofetch output.
[neofetch.txt](https://github.com/Axarva/dotfiles-2.0/files/6865845/neofetch.txt)

**Comment by Shahab96** [comment]
Strangely enough, the $logout case doesn't even work in the terminal directly.

![image](https://user-images.githubusercontent.com/826895/126720699-572b2959-1f32-4fdd-95a6-89f8941e9d56.png)

**Comment by Axarva** [comment]
Even though the command is fixed, would the menu work with eww?

**Comment by Shahab96** [comment]
Nope it isn't working with eww

**Comment by Kellegram** [comment]
Ahhh this is the issue I described in the discord, I troubleshooted this with TheEvilSkeleton for a whole day and it is at the end of the day fault of eww, specifically some update broke it. I don't remember if I ever found a way to resolve it.

**Comment by Vassili-Dev** [comment]
I found the source of this issue.

The button handling in [eww](https://github.com/elkowar/eww/blob/master/src/widgets/mod.rs)(lines 29-35) kills the process of the event handler script if it doesn't resolve in 200 milliseconds.

The nature of the confirmation dialogue means the script is going to be terminated before the user can type "yes".

You can even test this out by pressing a button that requires confirmation and typing "yes" REALLY REALLY fast.

Issue can be resolved by forking EWW and changing that behaviour.
Either that or remove the confirmation dialogue altogether.

**Comment by Shahab96** [comment]
It may be possible to modify the prompt to be shown before the script is invoked, I'll look into that.

**Comment by Vassili-Dev** [comment]
What worked for me is pulling eww and changing the `200` in [this line](https://github.com/elkowar/eww/blob/4f59424e0e82eb7ce76badb266974dd3e7ea6d8c/src/widgets/mod.rs#L29) to `20000`. It's not the most elegant solution, but it did the trick

**Comment by Kellegram** [comment]
Ahhh, great find, this only happened after a while, which means that eww dev must have changed the timer to be very low, weird decision, should probably open an issue regarding this.

**Comment by CyberBishop** [comment]
> What worked for me is pulling eww and changing the `200` in [this line](https://github.com/elkowar/eww/blob/4f59424e0e82eb7ce76badb266974dd3e7ea6d8c/src/widgets/mod.rs#L29) to `20000`, then rebuilding and replacing the binary in `~/bin`. It's not the most elegant solution, but it did the trick

this worked for me

**Comment by Axarva** [comment]
This will be fixed once the config migrates to yuck (It might take some time.)

**Comment by Axarva** [comment]
Fixed in 2df67e4
